package com.ferpa.argentinacampeon.common

object AnalyticsEvents {

    const val FIRST_OPEN = "first_time"
    const val FINISH_TUTORIAL_CAROUSEL = "finish_tutorial_carousel"
    const val FINISH_TUTORIAL = "finish_tutorial"
    const val VOTE_BOTTOM = "vote_bottom"
    const val VOTE_TOP = "vote_top"
    const val VERSUS_PLAYER_CLICK = "versus_player_click"
    const val VERSUS_MATCH_CLICK = "versus_match_click"
    const val VERSUS_PHOTOGRAPHER_CLICK = "versus_photographer_click"
    const val ADD_TO_FAVORITE = "add_favorite"
    const val DELETE_FAVORITE = "delete_favorite"
    const val SHARE_IMAGE = "share_image"
    const val NAV_PHOTO_DETAIL = "photo_detail"
    const val NAV_VERSUS = "nav_versus"
    const val NAV_FAVORITES = "nav_favorites"
    const val NAV_TOP = "nav_top"
    const val NAV_INFO = "nav_info"
    const val NAV_LIST = "nav_list"
    const val BEST_TAG_CLICK = "best_tag_click"
    const val BEST_PLAYER_CLICK = "best_player_click"
    const val BEST_MATCH_CLICK = "best_match_click"
    const val BEST_PHOTO_CLICK = "best_photo_click"
    const val BEST_BLOCKED_PHOTO_CLICK = "best_blocked_photo_click"
    const val LIST_PHOTO_CLICK = "list_photo_click"
    const val ABOUT_US_LINK_CLICK = "about_us_link_click"
    const val SELECT_LIST_PLAYER_CLICK = "select_list_player_click"
    const val SELECT_LIST_MATCH_CLICK = "select_list_match_click"
    const val SELECT_LIST_PHOTOGRAPHER_CLICK = "select_list_photographer_click"
    const val SELECT_LIST_TAG_CLICK = "select_list_tag_click"
    const val FORCE_UPDATE_MESSAGE = "force_update_message"
    const val FORCE_UPDATE_CLICK = "force_update_click"
    const val UPDATE_MESSAGE = "update_message"
    const val UPDATE_CLICK = "update_click"

}